window.imoveis = [
  {
    id: 1,
    nome: "Alameda Jardins",
    construtora: "FG",
    localizacao: "Centro, Balneário Camboriú",
    preco: "R$ 5.990.000,00",
    quartos: 4,
    suites: 4,
    vagas: 3,
    area: "170 m²",
    imagem: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=800",
    badge: "Exclusividade",
    tipo: "Apartamento",
    finalidade: "Compra",
    descricao: "Apartamento de alto padrão no coração de Balneário Camboriú, com vista definitiva para o mar. Acabamentos impecáveis e área de lazer completa em um dos endereços mais cobiçados da cidade.",
    youtube: ""
  },
  {
    id: 2,
    nome: "Ocean View",
    construtora: "Embraed",
    localizacao: "Barra Sul, Balneário Camboriú",
    preco: "R$ 8.500.000,00",
    quartos: 5,
    suites: 5,
    vagas: 4,
    area: "250 m²",
    imagem: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800",
    badge: "Alto Padrão",
    tipo: "Cobertura",
    finalidade: "Compra",
    descricao: "Cobertura duplex espetacular na Barra Sul. Piscina privativa, amplo terraço e living integrado com vista panorâmica de 360º para a orla de BC e Marina.",
    youtube: ""
  },
  {
    id: 3,
    nome: "Residencial Marbella",
    construtora: "Silva & Silva",
    localizacao: "Pioneiros, Balneário Camboriú",
    preco: "R$ 15.000,00 / mês",
    quartos: 3,
    suites: 1,
    vagas: 2,
    area: "120 m²",
    imagem: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800",
    badge: "Locação",
    tipo: "Apartamento",
    finalidade: "Locação",
    descricao: "Excelente apartamento para locação anual, finamente mobiliado, a poucos passos da praia e da nova Roda Gigante. Lazer completo no condomínio.",
    youtube: ""
  },
  {
    id: 4,
    nome: "Casa Alphaville",
    construtora: "Particular",
    localizacao: "Alphaville, Camboriú",
    preco: "R$ 4.200.000,00",
    quartos: 4,
    suites: 4,
    vagas: 4,
    area: "350 m²",
    imagem: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800",
    badge: "Oportunidade",
    tipo: "Casa",
    finalidade: "Compra",
    descricao: "Casa em condomínio fechado com projeto arquitetônico contemporâneo. Espaço gourmet amplo e integração perfeita com a natureza, oferecendo tranquilidade e segurança.",
    youtube: ""
  },
  {
    id: 5,
    nome: "Corporate Tower",
    construtora: "FG",
    localizacao: "Centro, Balneário Camboriú",
    preco: "R$ 1.200.000,00",
    quartos: 0,
    suites: 0,
    vagas: 1,
    area: "65 m²",
    imagem: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800",
    badge: "Comercial",
    tipo: "Sala Comercial",
    finalidade: "Compra",
    descricao: "Sala comercial de alto padrão em edifício corporativo moderno. Localização estratégica no centro comercial, ideal para clínicas, escritórios jurídicos ou startups.",
    youtube: ""
  },
  {
    id: 6,
    nome: "Villa Serena",
    construtora: "Embraed",
    localizacao: "Centro, Balneário Camboriú",
    preco: "R$ 4.800.000,00",
    quartos: 4,
    suites: 2,
    vagas: 3,
    area: "144 m²",
    imagem: "https://images.unsplash.com/photo-1600566753086-00f18efc2291?auto=format&fit=crop&q=80&w=800",
    badge: "Mobiliado",
    tipo: "Apartamento",
    finalidade: "Compra",
    descricao: "Apartamento clássico, finamente mobiliado e decorado, pronto para morar. Conta com uma área de lazer de resort, incluindo dezenas de opções de entretenimento.",
    youtube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  }
];
